version: "1.0"
stages:
  -"clone"
  -"checkmarx_scan"
steps:
  clone:
    title: "cloaning-repository"
    type: "git-clone"
    repo: "${{GIT_ORG}}/${{GIT_REPO}}"
    revision: ${{RELEASE_BRANCH}}
    stage: "clone"
    git: "${{GIT_PROVIDER}}"
  checkmarx_scan:
    type: freestyle
    stage: checkmarx_scan 
    image: "${{IMAGE_URL}}/cx-cli:latest"
    cmd:
      - -ProjectName
      - Test\testProject
      - -LocationPath
      - .
      - -LocationPathExclude
      - "**/.git/**/*, Nuget/**/*, build"
      - -cxtoken
      - ${{cx_token}}
      - -Incremental